spring.application.name=book_store_project


# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:books;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=musa
spring.datasource.password=musa
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console


# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



logging.level.org.springframework.jdbc=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

# or use devtools
spring.datasource.generate-unique-name=false
spring.datasource.name=booksaledb